# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 186f201fffdc4a4f52f7b2f598d6355f8a296abfc184fcfeba2ba5316a59ec544edf0e92f0734a35bab7e27a3038a90485120e703987b8a970fa5fb3962e0a59

test:
  secret_key_base: a11a7e9284c7e1bb7a8c2de2b03e687e9325fa2ef1f774f2d63541a8f02f957f1fce6a27b24b536bd14512e9da147c6e48fa51de2895afc989bf8f980a5f67d9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
